### PR TITLE
Statuses working on update page

### PR DESCRIPTION
**Pull request by Eyoung119**
- Log in
- update user page
- select something other than "online"

### CODE REVIEW

**Review by code-witch — APPROVED** [review]
yeehaw 💃

**Review by Xlayton — APPROVED** [review]
Looks good!

**Review by code-witch — APPROVED** [review]
yeeehaaaaaaaaaaaaaaaaaaaaaaaaaaw 🤰🤰🤰🤰🤰

**Review by LoganTyl — APPROVED** [review]
Looks good

**Pull request merged**
