### PR TITLE
Overhaul routes and establish base for paging

### PR DESCRIPTION
**Pull request by Xlayton**
The reviews for this one will mostly just be checking to see if previous stuff worked, and a quick glance at the code to see what has changed.

### CODE REVIEW

**Review by LoganTyl — APPROVED** [review]
Looks good

**Comment by Xlayton** [comment]
Now the webserver is included in the same server, which should make life easier.

**Review by Eyoung119 — APPROVED** [review]
Looks good!

**Review by code-witch — APPROVED** [review]
looks nice!

**Pull request merged**
