### PR TITLE
Added Log out and Friend Statuses

### PR DESCRIPTION
**Pull request by LoganTyl**
-Log in should be replaced with log out when logged in which destroys session
-Friend statuses can now be seen to left of friends' icon

### CODE REVIEW

**Review by Xlayton — CHANGES_REQUESTED** [review]
When 2 users log in, they both take the credentials of the first one logged in. I checked this behavior on master and found it wasn't present.

**Comment by Xlayton** [comment]
Nevermind, must've been some weird database bug or something.

**Review by Xlayton — APPROVED** [review]

**Review by Eyoung119 — APPROVED** [review]
Looks good! 🤠

**Review by code-witch — APPROVED** [review]
👠👙🎳

**Pull request merged**
