### PR TITLE
Theme changes in update user

### PR DESCRIPTION
**Pull request by Eyoung119**
-Sign in as a user
-Change your theme to another from dark

### CODE REVIEW

**Review by code-witch — CHANGES_REQUESTED** [review]
Doesn't work everytime

**Review by LoganTyl — APPROVED** [review]
Themes change sometimes; if that can be figured out, then great; otherwise, we'll deal with it

**Review by code-witch — APPROVED** [review]
💃

**Review by Xlayton — APPROVED** [review]
Alls working on this end

**Pull request merged**
