### PR TITLE
Basic Room Functionality and Public Servers Discoverability.

### PR DESCRIPTION
**Pull request by Xlayton**
Added in this update:
Room Creation
Joining Rooms
Limiting what rooms you can join to what rooms you are in

To Test:
Drop/Create Tables using new schema
Make an account
Log into said account
Make a room
Copy invite code
In a different browser make a new account, log in and then paste the url in your browser
It should redirect to the homepage with the room now on the left-hand side.
Boom you have rooms.

### CODE REVIEW

**Comment by Xlayton** [comment]
Public servers are now part of the pull request. Title updated.

**Review by LoganTyl — APPROVED** [review]
Looks and feels awesome

**Review by code-witch — APPROVED** [review]
doesnt work on edge at least for trying to chat, everything else does though 🦐

**Comment by Xlayton** [comment]
The Edge fix is part of the other pull request

**Pull request merged**
