### PR TITLE
Add style to homepage, also make the hompage and navigation. Also make chat into a pug file for future use.

### PR DESCRIPTION
**Pull request by Xlayton**

### CODE REVIEW

**Review by Eyoung119 — CHANGES_REQUESTED** [review]
The styling is a little broken for me on Chrome, the button falls outside the box and the lines don't match up properly. Some small fixes and it should be good.

**Comment by Xlayton** [comment]
> The styling is a little broken for me on Chrome, the button falls outside the box and the lines don't match up properly. Some small fixes and it should be good.

It wasn't chrome, it's because you're a boomer with 125% zoom. I know that other people have it though, so I fixed it.

**Review by Eyoung119 — APPROVED** [review]
Looks good! 🤠

**Review by LoganTyl — APPROVED** [review]
Looks good

**Review by code-witch — APPROVED** [review]
😋

**Pull request merged**
