### PR TITLE
User CRUD connected to PG & Signing in/out

### PR DESCRIPTION
**Pull request by LoganTyl**

### CODE REVIEW

**Review by Eyoung119 — APPROVED** [review]
Everything works, a little rough around the edges on functionality but I understand we have to do some more things. 🤠

**Review by Eyoung119 — APPROVED** [review]
Looks good! 🤠🤠

**Review by Xlayton — APPROVED** [review]
Looking good!

**Review by code-witch — APPROVED** [review]
🐸

**Pull request merged**
