### PR TITLE
Database

### PR DESCRIPTION
**Pull request by code-witch**
- Added models
- Added other tables and the creation script for those so you can have them
- Added a way to store image (strings) into the data base for user icons
- removed duplicates and tidied up some things

(also some of the views are broken on master and idk what happened pls send help)

### CODE REVIEW

**Review by Xlayton — APPROVED** [review]
Looks good to me :)

**Comment by Xlayton** [comment]
I fixed the paging 😄

**Review by Eyoung119 — APPROVED** [review]
Looks good!

**Review by LoganTyl — APPROVED** [review]
Looks good now

**Pull request merged**
