### PR TITLE
Loose ends

### PR DESCRIPTION
**Pull request by Xlayton**
Friends are now displayed when made
Profile picture now required for account creation
Reuploading profile picture every update no longer necessary

### CODE REVIEW

**Comment by Xlayton** [comment]
I'm going to be honest, this is probably the extent of the loose ends I plan on tying.

**Review by Eyoung119 — APPROVED** [review]
Looks good! 🤠

**Review by code-witch — APPROVED** [review]
no way to logout, and the user picture moves up with the server list

**Review by LoganTyl — APPROVED** [review]
Overall, looks good. Same issues that that Lua brought up exist, that being not being able to sign out and the profile picture moving upwards

**Pull request merged**
