### PR TITLE
Friends

### PR DESCRIPTION
**Pull request by LoganTyl**
Added friend lists and requests

-Drop and create tables
-Create 3 users
-Log into the first user
-Go to ugly /seeUsers page
-Click on Friend Requests link and enter third user's email
-Log out and do the same with the second user
-Log into the third user's account and click on Friend Requests
-Accept one user and reject the other
-Don't have a way on site to see friends, so check pgAdmin so accepted user and user 3 are friends

### CODE REVIEW

**Review by Eyoung119 — APPROVED** [review]
A little weird in places but functionality works fine. We talked about why the seeUsers page is a little odd
🤠

**Review by Xlayton — CHANGES_REQUESTED** [review]
Routes 115 and 135 change GetUser to GetUserById

**Review by Xlayton — APPROVED** [review]
Thanks for changes.

**Review by code-witch — APPROVED** [review]
🍑

**Pull request merged**
